snakesite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("workflow.urls", namespace="workflow")),
    path("api/", include("wms_api.urls", namespace="wms_api")),
    path("user/", include("users.urls", namespace="user")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import (
    avatar_image_request,
    logout_request,
    profile_request,
    register_request,
    rnd_avatar_request,
)

app_name = "users"

urlpatterns = [
    path("register/", register_request, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("logout/", logout_request, name="logout"),
    path("profile/", profile_request, name="profile"),
    path("random-avatar/", rnd_avatar_request, name="avatar"),
    path("avatar.<seed>.png", avatar_image_request, name="avatar-rnd"),
]

workflow/urls.py
from django.urls import path

from .views import (
    DashboardView,
    IndexView,
    MessageDetailView,
    ResultDetailsView,
    ResultListView,
    RunDeleteView,
    RunDetailView,
    RunListView,
    WorkflowCreateView,
    WorkflowDeleteView,
    WorkflowDetailView,
    WorkflowListView,
    WorkflowSettingUpdateView,
    WorkflowTemplateCreateView,
    WorkflowTemplateDeleteView,
    WorkflowTemplateDetailView,
    WorkflowTemplateListView,
    WorkflowTemplateSettingDetailView,
    WorkflowTemplateSettingUpdateView,
    WorkflowTemplateUpdateView,
    WorkflowUpdateView,
    download_report,
    report_view,
    run_create_view,
)

app_name = "workflow"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("template/new/", WorkflowTemplateCreateView.as_view(), name="template-create"),
    path("templates/", WorkflowTemplateListView.as_view(), name="templates"),
    path(
        "template/<int:pk>/",
        WorkflowTemplateDetailView.as_view(),
        name="template-detail",
    ),
    path(
        "template/<int:pk>/update/",
        WorkflowTemplateUpdateView.as_view(),
        name="template-update",
    ),
    path(
        "template/<int:pk>/delete/",
        WorkflowTemplateDeleteView.as_view(),
        name="template-delete",
    ),
    path(
        "template/setting/<int:pk>/",
        WorkflowTemplateSettingDetailView.as_view(),
        name="template-setting",
    ),
    path(
        "template/setting/<int:pk>/update/",
        WorkflowTemplateSettingUpdateView.as_view(),
        name="template-setting-update",
    ),
    path("workflows/", WorkflowListView.as_view(), name="workflows"),
    path("workflow/new/", WorkflowCreateView.as_view(), name="workflow-create"),
    path(
        "workflow/new/<int:template_id>/",
        WorkflowCreateView.as_view(),
        name="workflow-create",
    ),
    path("workflow/<int:pk>/", WorkflowDetailView.as_view(), name="workflow-detail"),
    path(
        "workflow/<int:pk>/update/",
        WorkflowUpdateView.as_view(),
        name="workflow-update",
    ),
    path(
        "workflow/<int:pk>/delete/",
        WorkflowDeleteView.as_view(),
        name="workflow-delete",
    ),
    path(
        "workflow/setting/<int:pk>/update/",
        WorkflowSettingUpdateView.as_view(),
        name="workflow-setting-update",
    ),
    path("runs/", RunListView.as_view(), name="runs"),
    path("run/new/<int:workflow_id>/", run_create_view, name="run-create"),
    path("run/<int:pk>/", RunDetailView.as_view(), name="run-details"),
    path("run/<int:pk>/delete/", RunDeleteView.as_view(), name="run-delete"),
    path("results/", ResultListView.as_view(), name="results"),
    path("result/<int:pk>/", ResultDetailsView.as_view(), name="results-details"),
    path("report/<int:pk>/", report_view, name="report"),
    path("messages/<int:pk>/", MessageDetailView.as_view(), name="run-messages"),
    path("download-report/<int:pk>/", download_report, name="download-report"),
]

workflow/forms.py
from django import forms

from .models import Run, RunInputFile


class RunCreateForm(forms.ModelForm):
    class Meta:
        model = Run
        fields = [
            "sample_sheet",
            "config",
            "target",
            "cores",
            "run_is_private",
            "args",
            "environment_variable",
        ]


class InputFilesCreateForm(forms.ModelForm):
    class Meta:
        model = RunInputFile
        fields = ["input_data"]
        widgets = {
            "input_data": forms.ClearableFileInput(attrs={"multiple": True}),
        }

workflow/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import FileResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
)

from .forms import InputFilesCreateForm, RunCreateForm
from .models import (
    Result,
    Run,
    RunInputFile,
    Workflow,
    WorkflowSetting,
    WorkflowStatus,
    WorkflowTemplate,
    WorkflowTemplateSetting,
)


class IndexView(TemplateView):
    template_name = "workflow/index.html"


class DashboardView(ListView):
    model = Run
    ordering = ["-date_created"]
    template_name = "workflow/dashboard.html"


class WorkflowTemplateListView(ListView):
    model = WorkflowTemplate
    paginate_by = 6


class WorkflowTemplateCreateView(LoginRequiredMixin, CreateView):
    model = WorkflowTemplate
    fields = ["name", "description", "url", "contributors"]


class WorkflowTemplateUpdateView(LoginRequiredMixin, UpdateView):
    model = WorkflowTemplate
    fields = ["name", "description", "url", "contributors"]


class WorkflowTemplateDetailView(DetailView):
    model = WorkflowTemplate


class WorkflowTemplateDeleteView(LoginRequiredMixin, DeleteView):
    model = WorkflowTemplate

    def get_success_url(self):
        return reverse("workflow:templates")


class WorkflowTemplateSettingDetailView(DetailView):
    model = WorkflowTemplateSetting


class WorkflowTemplateSettingUpdateView(LoginRequiredMixin, UpdateView):
    model = WorkflowTemplateSetting
    fields = ["path_snakefile", "path_sample_sheet", "path_config"]


class WorkflowCreateView(LoginRequiredMixin, CreateView):
    model = Workflow
    fields = ["workflow_template", "name"]

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def get_initial(self):
        if self.kwargs.get("template_id"):
            workflow_template = get_object_or_404(
                WorkflowTemplate, pk=self.kwargs.get("template_id")
            )
            return {
                "workflow_template": workflow_template,
            }


class WorkflowDetailView(DetailView):
    model = Workflow


class WorkflowListView(ListView):
    model = Workflow
    paginate_by = 6


class WorkflowDeleteView(LoginRequiredMixin, DeleteView):
    model = Workflow

    def get_success_url(self):
        return reverse("workflow:workflows")


class WorkflowUpdateView(LoginRequiredMixin, UpdateView):
    model = Workflow
    fields = ["name", "accessible_by"]
    template_name = "workflow/workflow_update_form.html"


class WorkflowSettingUpdateView(LoginRequiredMixin, UpdateView):
    model = WorkflowSetting
    fields = ["path_snakefile", "path_sample_sheet", "path_config"]
    template_name = "workflow/workflowsetting_update_form.html"


@login_required
def run_create_view(request, workflow_id):
    workflow_instance = Workflow.objects.get(id=workflow_id)

    workflow_blocked = (
        workflow_instance.Status == "RUNNING" or workflow_instance.Status == "QUEUED"
    )

    if request.method == "POST":
        run_form = RunCreateForm(request.POST, request.FILES)
        file_form = InputFilesCreateForm(request.POST, request.FILES)

        if run_form.is_valid() and file_form.is_valid() and not workflow_blocked:
            # complete the run form
            run_instance = run_form.save(commit=False)
            run_instance.workflow = workflow_instance
            run_instance.created_by = request.user
            run_instance.save()

            # upload the files
            files = request.FILES.getlist("input_data")
            for f in files:
                file_instance = RunInputFile(input_data=f, run=run_instance)
                file_instance.save()

            # change status of workflow
            WorkflowStatus.objects.create(
                workflow=Workflow.objects.get(pk=workflow_id),
                status="QUEUED",
            )

            messages.success(request, "Your run has been queued!")
            return redirect("workflow:run-details", pk=run_instance.pk)

        if not run_form.is_valid():
            messages.error(
                request,
                "Unsuccessful run start. Please check the sample sheet, config, target or cores.",
            )

        if not file_form.is_valid():
            messages.error(
                request, "Unsuccessful run start. Please check the input file."
            )

        if workflow_blocked:
            messages.error(
                request,
                (
                    f"{ workflow_instance.name } is currently processing. ",
                    "Please wait for the old run to be completed before submitting a new one.",
                ),
            )

    else:
        run_form = RunCreateForm()
        file_form = InputFilesCreateForm()

    context = {
        "run_form": run_form,
        "file_form": file_form,
        "workflow_instance": workflow_instance,
        "workflow_status": workflow_instance.Status,
        "workflow_block": workflow_blocked,
    }

    return render(request, "workflow/run_form.html", context)


class RunDetailView(DetailView):
    model = Run

    def get_context_data(self, *args, **kwargs):
        context = super(RunDetailView, self).get_context_data(*args, **kwargs)
        context["run_list"] = Run.objects.all().order_by("-date_created")
        return context


class RunDeleteView(LoginRequiredMixin, DeleteView):
    model = Run

    def get_success_url(self):
        return reverse(
            "workflow:workflow-detail", kwargs={"pk": self.object.workflow.id}
        )


class RunListView(ListView):
    model = Run
    paginate_by = 6
    context_object_name = "run_list"
    ordering = ["-date_created"]


class ResultListView(ListView):
    model = Result
    paginate_by = 6
    ordering = ["-date_created"]


class ResultDetailsView(DetailView):
    model = Result


class MessageDetailView(DeleteView):
    model = Run
    template_name = "workflow/message_detail.html"


def report_view(request, pk):
    result = Result.objects.get(pk=pk)
    return render(request, result.path_index_report)


def download_report(request, pk):
    result = Result.objects.get(id=pk)
    filename = result.path_result_zip
    response = FileResponse(open(filename, "rb"))
    return response

workflow/templates/workflow/dashboard.html
{% extends "workflow/project_base.html" %}
{% block title %}Snakesite Dashboard{% endblock title %}
{% block nav_item_dashboard %}active{% endblock nav_item_dashboard %}
{% block content %}
  <div class="container-fluid bg-light p-4 mb-4">
    <h1>Dashboard</h1>
  </div>
  <div class="container-fluid bg-light p-4 mb-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center border-bottom">
        <h2>Runs Over Time</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
            This week
          </button>
        </div>
      </div>
      <canvas class="my-4 w-100 chartjs-render-monitor" id="myChart" width="876" height="369" style="display: block; width: 876px; height: 369px;"></canvas>
    </div>
    
    <div class="container-fluid bg-light p-4 mb-4">
      <h2>Run Surveillance</h2>
      <div class="table-responsive">
        <table class="table table-sm table-hover align-middle">
          <thead class="thead-dark">
            <tr>
              <th>Run</th>
              <th>Date</th>
              <th>Workflow</th>
              <th>Status</th>
              <th>Progress</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>999</td>
              <td>2021-12-31</td>
              <td>Example</td>
              <td>Queued</td>
              <td> 
                <div class="progress">
                  <div class="progress-bar bg-info w-0" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </td>
            </tr>
            <tr>
              <td>999</td>
              <td>2021-12-31</td>
              <td>Example</td>
              <td>Testing</td>
              <td> 
                <div class="progress">
                  <div class="progress-bar bg-info w-0" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </td>
            </tr>
            <tr>
              <td>999</td>
              <td>2021-12-31</td>
              <td>Example</td>
              <td>Running</td>
              <td> 
                <div class="progress">
                  <div class="progress-bar bg-warning text-dark progress-bar-striped progress-bar-animated w-50 " role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">50%</div>
                </div>
              </td>
            </tr>
            <tr>
              <td>999</td>
              <td>2021-12-31</td>
              <td>Example</td>
              <td>Running</td>
              <td> 
                <div class="progress">
                  <div class="progress-bar bg-warning text-dark progress-bar-striped progress-bar-animated w-75 " role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">75%</div>
                </div>
              </td>
            </tr>
            <tr>
              <td>999</td>
              <td>2021-12-31</td>
              <td>Example</td>
              <td>Finished</td>
              <td> 
                <div class="progress">
                  <div class="progress-bar bg-success w-100" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </td>
            </tr>
            <tr>
            <tr>
              <td>999</td>
              <td>2021-12-31</td>
              <td>Example</td>
              <td>Failed</td>
              <td> 
                <div class="progress">
                  <div class="progress-bar bg-danger w-100" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </td>
            </tr>
            {% for run in object_list %}
            <tr>
              <td><a class="text-decoration-none text-reset" href="{% url 'workflow:run-details' run.id %}">{{ run.id }}</a></td>
              <td><a class="text-decoration-none text-reset" href="{% url 'workflow:run-details' run.id %}">{{ run.date_created|date:'Y-m-d'}}</a></td>
              <td><a class="text-decoration-none text-reset" href="{% url 'workflow:run-details' run.id %}">{{ run.workflow.name }}</a></td>
              <td><a class="text-decoration-none text-reset" href="{% url 'workflow:run-details' run.id %}">{{ run.Status }}</a></td>
              <td>
                {% if run.Status == "Created" or run.Status == "Queued" %}
                  <div class="progress">
                    <div class="progress-bar bg-info w-0" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                {% elif run.Status == "Testing" %}
                  <div class="progress">
                    <div class="progress-bar bg-info w-100" role="progressbar" aria-valuenow="1" aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                {% elif run.Status == "Running" %}
                <div class="progress">
                  <div class="progress-bar bg-info w-100" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">50</div>
                </div>
                {% elif run.Status == "Generate Report" %}
                  <div class="progress">
                    <div class="progress-bar bg-warning w-100" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                {% elif run.Status == "Finished" %}
                  <div class="progress">
                    <div class="progress-bar bg-success w-100" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                {% elif run.Status == "Failed" %}
                  <div class="progress">
                    <div class="progress-bar bg-danger w-100" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                {% else %}
                  {{run.Status}}
                {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
{% endblock content %}

workflow/templates/workflow/message_detail.html
{% load static %}

    <div class="container-fluid bg-light p-4 mb-4"> 
        {{ object.MessageHeaders }}

        <table class="table table-hover" id="messageTable">
            <thead>
                <tr>
                <th>Timestamp</th>
                <th>Level</th>
                <th>Other</th>
                <th>Info</th>
                <th></th>
                </tr>
            </thead>
            <tbody>
                {% for msg in object.Messages %}
                <tr>
                    <td>{{ msg.snakemake_timestamp|date:"G:i:s" }}</td>
                    <td>{{ msg.message.level }}</td>
                    <th>Job</th>
                    <td style ="word-break:break-all;">{{ msg.message.job }}</td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <th>Status</th>
                    <td style ="word-break:break-all;">{{ msg.message.status }}</td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <th>Message</th>
                    <td style ="word-break:break-all;">{% if msg.message.exception %}{{ msg.message.exception }} {% endif %}{{ msg.message.msg }}</td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <th>File</th>
                    <td style ="word-break:break-all;">{{ msg.message.file }}</td>
                    <td></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% block javascript %}
<script id="websocket_run_messages" run_id="{{ object.id }}" type="text/javascript" src="{% static 'workflow/js/websocket_run_messages.js' %}"></script>
{% endblock javascript %}

workflow/templates/workflow/project_base.html
{% extends "base/base.html" %}
{% load static %}
{% block css %}<link href="{% static 'workflow/workflow.css' %}" rel="stylesheet" >{% endblock css %}
   

workflow/templates/workflow/run_detail.html
{% extends "workflow/project_base.html" %}
{% block title %}Run {{ object.id }} of {{ object.workflow.name}}{% endblock title %}
{% load static %}

{% block content %}
  <div class="container-fluid bg-light p-4 mb-4">
    <h1 >Run {{ object.id }}</h1>
    <p class="lead text-muted">in {{ object.workflow.name}}</p> 
    <a href="#" class="btn btn-outline-primary">Restart</a>
    <a href="#" class="btn btn-outline-warning">Cancel</a>
    <a href="{% url 'workflow:run-delete' object.id %}" class="btn btn-outline-danger">Delete</a>
    <a href="{% url 'workflow:runs'%}" class="btn btn-outline-secondary">Back</a>
  </div>

  <div class="container-fluid bg-light p-4 mb-4">
    <h2>Information</h2>
    <table class="table">
        <tr>
          <th scope="row">Progress</th>
          <td id="run_progress_cell">{{ object.Progress }}</td>
        </tr>
        <tr>
          <th scope="row">Status</th>
          <td  id="run_status_cell">{{ object.Status }}</td>
        </tr>
        <tr>
          <th scope="row">Started by</th>
          <td>
              {{ object.created_by.get_username }}
          </td>
        </tr>
        <tr>
          <th scope="row">Date Created</th>
          <td>{{ object.date_created }}</td>
        </tr>
        <tr>
          <th scope="row">Target</th>
          <td>{{ object.target }}</td>
        </tr>
        <tr>
          <th scope="row">Cores</th>
          <td>{{ object.cores }}</td>
        </tr>
        <tr>
          <th scope="row">Is Private</th>
          <td>{{ object.run_is_private }}</td>
        </tr>
        </tr>
        </tr>
        <tr>
          <th scope="row">Sample Sheet</th>
          <td>{{ object.sample_sheet }}</td>
        </tr>
        </tr>
        <tr>
          <th scope="row">Input Files</th>
          <td></td>
        </tr>
        {% if object.Results %}
        <tr>
          <th scope="row">Report</th>
          <td>
          {% for result in object.Results %}
            <a  href="{% url 'workflow:download-report' result.id %}" download>Download</a> <br>
          {% endfor %}
          </td>
        </tr>
        {% endif %}
      </tbody>
    </table>
  </div>


  <!-- messages -->
  {% include 'workflow/message_detail.html' %}

{% endblock content %}

{% block javascript %}
<script id="websocket_run_progress" run_id="{{ object.id }}" type="text/javascript" src="{% static 'workflow/js/websocket_run_progress.js' %}"></script>
<script id="websocket_run_status" run_id="{{ object.id }}" type="text/javascript" src="{% static 'workflow/js/websocket_run_status.js' %}"></script>
{% endblock javascript %}

workflow/templates/workflow/workflow_confirm_delete.html
{% extends "workflow/project_base.html" %}
{% block title %}{{ object.name }}{% endblock title %}
{% block nav_item_templates %}active{% endblock nav_item_templates %}
{% block content %}

    <div class="container-fluid bg-light p-4 mb-4">
        <h1>Are you sure you want to delete the workflow "{{ object.name }}?"</h1>
        <p class="lead">All runs and results will be permanently lost!</p>
    </div>  
    <div class="container-fluid bg-light p-4 mb-4">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <button type="submit" class="btn btn-outline-danger">Yes, Delete</button>
                <a href="{% url 'workflow:workflow-detail' object.id %}" class="btn btn-outline-secondary">Cancel</a>
            </fieldset>
        </form>
    </div>
{% endblock content %}

workflow/templates/workflow/workflow_detail.html
{% extends "workflow/project_base.html" %}
{% block title %}{{ object.name }}{% endblock title %}
{% block nav_item_workflow %}active{% endblock nav_item_workflow %}
{% block content %}

  <div class="container-fluid bg-light p-4 mb-4">
    <h1>{{ object.name }}</h1>
    <p class="lead text-muted">{{ object.workflow_template.description }}</p> 
    <a href="{% url 'workflow:run-create' object.id %}" class="btn btn-outline-success">Start a run</a>
  </div>

  <div class="container-fluid bg-light p-4 mb-4">
    <h2>Information</h2>
    <table class="table">
      <tbody>
        <tr>
          <th scope="row">Template</th>
          <td><a href="{% url 'workflow:template-detail' object.workflow_template.id %}" class="text-decoration-none text-reset">{{ object.workflow_template.name }}</a></td>
        </tr>
        <tr>
          <th scope="row">Workflow ID</th>
          <td>{{ object.id }}</td>
        </tr>
        <tr>
          <th scope="row">Owner</th>
          <td>
              {{ object.created_by.get_username }}<br>
          </td>
        </tr>
        <tr>
          <th scope="row">Accessible by</th>
          <td>
            {% for contributor in object.accessible_by.all %}
              {{contributor.get_username}} <br>
            {% endfor %}
          </td>
        </tr>
        <tr>
          <th scope="row">Date Created</th>
          <td>{{ object.date_created }}</td>
        </tr>
        <tr>
          <th scope="row">Number of runs</th>
          <td>{{ object.NumRuns }}</td>
        </tr>
        <tr>
          <th scope="row">Path to Snakefile</th>
          <td>{{ object.Setting.path_snakefile }}</td>
        </tr>
        <tr>
          <th scope="row">Path to Sample Sheet</th>
          <td>{{ object.Setting.path_sample_sheet }}</td>
        </tr>
        <tr>
          <th scope="row">Path to Config</th>
          <td>{{ object.Setting.path_config }}</td>
        </tr>
        <tr>
          <th scope="row">Status</th>
          <td>{{ object.Status }}</td>
        </tr>

      </tbody>
    </table>
  </div>

  <div class="container-fluid bg-light p-4 mb-4">
    <a href="{% url 'workflow:workflow-update' object.id %}" class="btn btn-outline-primary">Update workflow</a>
    <a href="{% url 'workflow:workflow-setting-update' object.Setting.id %}" class="btn btn-outline-primary">Update paths</a>
    <a href="{% url 'workflow:workflow-delete' object.id %}" class="btn btn-outline-danger">Delete workflow</a>
    <a href="{% url 'workflow:workflows' %}" class="btn btn-outline-secondary">Back to all workflows</a>
  </div>


  <div class="container-fluid bg-light p-4 mb-4">
    <h2>Runs</h2>
    Some overview over the runs. Maybe with link to results.

  </div>

{% endblock content %}

workflow/templates/workflow/workflowtemplate_detail.html
{% extends "workflow/workflowtemplate_detail_base.html" %}

  {% block template_detail_header %}
    <h1 class>{{ object.name }}</h1>
    <p class="lead text-muted">{{ object.description }}</p> 
  {% endblock template_detail_header%}

  {% block template_active_information %}active{% endblock template_active_information %}

  {% block template_detail_content %}
    <table class="table">
      <tbody>
        <tr>
          <th scope="row">Template ID</th>
          <td>{{ object.id }}</td>
        </tr>
        <tr>
          <th scope="row">Homepage</th>
          <td><a href="{{ object.url }}" class="text-decoration-none text-reset">{{ object.url }}</a></td>
        </tr>
        <tr>
          <th scope="row">Owner</th>
          <td>
            {% for owner in object.owner.all %}
              {{owner.get_username}}<br>
            {% endfor %}
          </td>
        </tr>
        <tr>
          <th scope="row">Contributors</th>
          <td>
            {% for contributor in object.contributors.all %}
              {{contributor.get_username}} <br>
            {% endfor %}
          </td>
        </tr>
        <tr>
          <th scope="row">Date Created</th>
          <td>{{ object.date_created }}</td>
        </tr>
        <tr>
          <th scope="row">Date Modified</th>
          <td>{{ object.date_modified }}</td>
        </tr>
      </tbody>
    </table>
  {% endblock template_detail_content %}

  {% block template_detail_button %}
    <a href="{% url 'workflow:template-update' object.id %}" class="btn btn-outline-primary">Update template</a>
  {% endblock template_detail_button %}

workflow/templates/workflow/workflowtemplate_detail_base.html
{% extends "workflow/project_base.html" %}
{% block title %}{{ object.name }}{% endblock title %}
{% block nav_item_templates %}active{% endblock nav_item_templates %}
{% block content %}  
  <div class="container-fluid bg-light p-4 mb-4">
    {% block template_detail_header %}{% endblock template_detail_header%} 
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link {% block template_active_information %}{% endblock template_active_information %}" aria-current="page" href="{% url 'workflow:template-detail' object.id %}">Information</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% block template_active_settings %}{% endblock template_active_settings %}" href="{% url 'workflow:template-setting' object.id %}">Settings</a>
      </li>
    </ul>
    {% block template_detail_content %}{% endblock template_detail_content%}
  </div>  

  <div class="container-fluid bg-light p-4">
      {% block template_detail_button %}{% endblock template_detail_button %}
      <a href="{% url 'workflow:template-delete' object.id %}" class="btn btn-outline-danger">Delete template</a>
      <a href="{% url 'workflow:templates' %}" class="btn btn-outline-secondary">Back to all templates</a>
  </div>  
{% endblock content %}