snakesite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("workflow.urls", namespace="workflow")),
    path("api/", include("wms_api.urls", namespace="wms_api")),
    path("user/", include("users.urls", namespace="user")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import (
    avatar_image_request,
    logout_request,
    profile_request,
    register_request,
    rnd_avatar_request,
)

app_name = "users"

urlpatterns = [
    path("register/", register_request, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("logout/", logout_request, name="logout"),
    path("profile/", profile_request, name="profile"),
    path("random-avatar/", rnd_avatar_request, name="avatar"),
    path("avatar.<seed>.png", avatar_image_request, name="avatar-rnd"),
]

users/models.py
from django.contrib.auth.models import User
from django.db import models
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="avatars/")

    def __str__(self):
        return f"{self.user.username} Profile"

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        if not self.image.path.endswith(".svg"):
            img = Image.open(self.image.path)
            if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)
                img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Profile


class ProfileCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(ProfileCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email"]


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["image"]

users/views.py
import io
import os
import random

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.utils.cache import add_never_cache_headers, patch_cache_control

from .forms import ProfileCreateForm, ProfileUpdateForm, UserUpdateForm
from .models import Profile
from .utils import create_avatar_image, generate_avatar


def register_request(request):
    if request.method == "POST":
        form = ProfileCreateForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(
                request, "Registration successful. You are now able to log in."
            )
            return redirect("user:login")
        messages.error(
            request, "Unsuccessful registration. Please check the provided information."
        )
    form = ProfileCreateForm
    return render(
        request=request,
        template_name="users/register.html",
        context={"register_form": form},
    )


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("workflow:index")


@login_required
def profile_request(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile
        )
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, "Your profile hast been updated!")
            return redirect("user:profile")
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {"u_form": u_form, "p_form": p_form}

    return render(request, "users/profile.html", context)


def rnd_avatar_request(request):
    if request.method == "POST":
        seed = request.POST.get("seed")
        instance = Profile.objects.get(id=request.user.profile.pk)
        abs_img = "".join([os.path.join(settings.AVATARS, str(seed)), ".svg"])
        rel_img = "".join(
            [os.path.join(os.path.basename(settings.AVATARS), str(seed)), ".svg"]
        )
        create_avatar_image(abs_img, seed=seed)
        instance.image = rel_img
        instance.save()
        # messages.success(request, "Your avatar hast been updated!" )
        return redirect("user:profile")

    context = {"rnd_seed": random.randint(1, 100000)}

    return render(request, "users/avatar.html", context)


def avatar_image_request(request, seed=None):
    bytes = io.BytesIO()
    avatar = generate_avatar(seed)
    avatar.render_png_file(bytes)
    response = HttpResponse(bytes.getvalue())
    response["content-type"] = "image/png"
    if seed == "random":
        add_never_cache_headers(response)
    else:
        patch_cache_control(response, max_age=60, public=True)

    return response

users/templates/users/avatar.html
{% extends "base/base.html" %}
{% block title %}Profile{% endblock title %}
{% block nav_item_profile %}active{% endblock nav_item_profile %}
{% block content %}      
{% load crispy_forms_tags %}
<div class=" d-flex align-items-center justify-content-center">
        <p>
        <img class="rounded-circle account-img align-middle" src="{% url 'users:avatar-rnd' rnd_seed  %}"/> <br>
      </p>
      <p>
        <form method="POST" enctype="multipart/form-data" class="pt-2 pl-2">        
            {% csrf_token %}    
            <input type="hidden" name="seed" value="{{ rnd_seed }}" />
            <a class="btn btn-outline-primary" href="{% url 'user:avatar' %}"">Another one!</a>
            <button class="btn btn-outline-success" type="submit">Use this Avatar</button>
            <a class="btn btn-outline-danger" href="{% url 'user:profile' %}"">Nah, keep old one</a>
        </form>
      </p>
</div>
{% endblock content %}  

users/templates/users/login.html
{% extends "workflow/project_base.html" %}
{% block title %}Login{% endblock title %}
{% block nav_item_profile %}active{% endblock nav_item_profile %}
{% block content %}      
{% load crispy_forms_tags %}

  <div class="container-fluid bg-light p-4 mb-4">
    <!--Login--> 
    <div class="form-signin">
      <h1>Login</h1>
      <form method="POST" class="mb-4">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Login</button>
      </form>
      <p class="text-muted">Don't have an account? <a class="text-muted" href="{% url 'user:register' %}">Create an account</a>.</p>
    </div>
  </div>

{% endblock %}

users/templates/users/profile.html
{% extends "workflow/project_base.html" %}
{% block title %}Profile{% endblock title %}
{% block nav_item_profile %}active{% endblock nav_item_profile %}
{% block content %}      
{% load crispy_forms_tags %}

<div class="container-fluid bg-light p-4 mb-4">
    <p class= "pb-4">
      <img style="float:left" class="rounded-circle col-md-2 account-img" src="{{ user.profile.image.url }}"/>
      <h1 class="content-heading">{{ user.username }}</h1>
      {{ user.email }}
      <p  class="small text-muted pt-4">
        <a class="text-muted" href="{% url 'user:avatar' %}">
          Not happy with your avatar? 
          Create a new one!</a>
      </p>
    </p>

    <p style="clear:both" class ="pt-5">
    
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ u_form|crispy }}                    
    {{ p_form|crispy }}  
    <p class ="pt-2"></p>            
    <button class="btn btn-outline-primary" type="submit">Update Profile</button>
    </form>
    </p>
</div>

{% endblock content %}  s

users/templates/users/register.html
{% extends "workflow/project_base.html" %}
{% block title %}Register{% endblock title %}
{% block nav_item_profile %}active{% endblock nav_item_profile %}
{% block content %}
{% load crispy_forms_tags %}         

	<div class="container-fluid bg-light p-4 mb-4">
		<h1>Register</h1>
		<form method="POST" class= mb-4>
			{% csrf_token %}
			{{ register_form|crispy }}                    
			<button class="btn btn-primary" type="submit">Register</button>
		</form>
		<p class="text-muted">If you already have an account, <a class="text-muted" href="{% url 'user:login' %}">login instead</a>.</p>
	</div>

{% endblock %}