snakesite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("workflow.urls", namespace="workflow")),
    path("api/", include("wms_api.urls", namespace="wms_api")),
    path("user/", include("users.urls", namespace="user")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import (
    avatar_image_request,
    logout_request,
    profile_request,
    register_request,
    rnd_avatar_request,
)

app_name = "users"

urlpatterns = [
    path("register/", register_request, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("logout/", logout_request, name="logout"),
    path("profile/", profile_request, name="profile"),
    path("random-avatar/", rnd_avatar_request, name="avatar"),
    path("avatar.<seed>.png", avatar_image_request, name="avatar-rnd"),
]

workflow/urls.py
from django.urls import path

from .views import (
    DashboardView,
    IndexView,
    MessageDetailView,
    ResultDetailsView,
    ResultListView,
    RunDeleteView,
    RunDetailView,
    RunListView,
    WorkflowCreateView,
    WorkflowDeleteView,
    WorkflowDetailView,
    WorkflowListView,
    WorkflowSettingUpdateView,
    WorkflowTemplateCreateView,
    WorkflowTemplateDeleteView,
    WorkflowTemplateDetailView,
    WorkflowTemplateListView,
    WorkflowTemplateSettingDetailView,
    WorkflowTemplateSettingUpdateView,
    WorkflowTemplateUpdateView,
    WorkflowUpdateView,
    download_report,
    report_view,
    run_create_view,
)

app_name = "workflow"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("template/new/", WorkflowTemplateCreateView.as_view(), name="template-create"),
    path("templates/", WorkflowTemplateListView.as_view(), name="templates"),
    path(
        "template/<int:pk>/",
        WorkflowTemplateDetailView.as_view(),
        name="template-detail",
    ),
    path(
        "template/<int:pk>/update/",
        WorkflowTemplateUpdateView.as_view(),
        name="template-update",
    ),
    path(
        "template/<int:pk>/delete/",
        WorkflowTemplateDeleteView.as_view(),
        name="template-delete",
    ),
    path(
        "template/setting/<int:pk>/",
        WorkflowTemplateSettingDetailView.as_view(),
        name="template-setting",
    ),
    path(
        "template/setting/<int:pk>/update/",
        WorkflowTemplateSettingUpdateView.as_view(),
        name="template-setting-update",
    ),
    path("workflows/", WorkflowListView.as_view(), name="workflows"),
    path("workflow/new/", WorkflowCreateView.as_view(), name="workflow-create"),
    path(
        "workflow/new/<int:template_id>/",
        WorkflowCreateView.as_view(),
        name="workflow-create",
    ),
    path("workflow/<int:pk>/", WorkflowDetailView.as_view(), name="workflow-detail"),
    path(
        "workflow/<int:pk>/update/",
        WorkflowUpdateView.as_view(),
        name="workflow-update",
    ),
    path(
        "workflow/<int:pk>/delete/",
        WorkflowDeleteView.as_view(),
        name="workflow-delete",
    ),
    path(
        "workflow/setting/<int:pk>/update/",
        WorkflowSettingUpdateView.as_view(),
        name="workflow-setting-update",
    ),
    path("runs/", RunListView.as_view(), name="runs"),
    path("run/new/<int:workflow_id>/", run_create_view, name="run-create"),
    path("run/<int:pk>/", RunDetailView.as_view(), name="run-details"),
    path("run/<int:pk>/delete/", RunDeleteView.as_view(), name="run-delete"),
    path("results/", ResultListView.as_view(), name="results"),
    path("result/<int:pk>/", ResultDetailsView.as_view(), name="results-details"),
    path("report/<int:pk>/", report_view, name="report"),
    path("messages/<int:pk>/", MessageDetailView.as_view(), name="run-messages"),
    path("download-report/<int:pk>/", download_report, name="download-report"),
]

base/templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Favicon -->
    <link href="{% static 'base/img/favicon.ico' %}" rel="icon" type="image/x-icon" />

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    {% block css %}{% endblock css %}

    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <div class="container">
      <!-- Navbar -->
      {% include 'base/navbar.html' %}
      
      <div class="container-fluid p-0 m-4"></div>

      <!-- Messages -->
      <div class="container-fluid p-0">
        {% include 'base/message.html' %}
      </div>
      
      <!-- Content -->
      <div class="container-fluid p-0">
        {% block content %}{% endblock %}
      </div>
    </div>
    
    {% block javascript %}{% endblock javascript %}

    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>

base/templates/base/message.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert" >
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

base/templates/base/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'workflow:index'%}">
        <img src="{% static 'base/img/snakemake-logo.png' %}" alt="" width="24" height="24" class="d-inline-block align-text-top">
        Snakesite
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link {% block nav_item_home %}{% endblock nav_item_home %}"href="{% url 'workflow:index'%}"">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% block nav_item_dashboard %}{% endblock nav_item_dashboard %}"href="{% url 'workflow:dashboard'%}"">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% block nav_item_templates %}{% endblock nav_item_templates %}" href="{% url 'workflow:templates'%}"">Templates</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% block nav_item_workflow %}{% endblock nav_item_workflow %}" href="{% url 'workflow:workflows'%}">Workflows</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% block nav_item_runs %}{% endblock nav_item_runs %}" href="{% url 'workflow:runs' %}">Runs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% block nav_item_results %}{% endblock nav_item_results %}" href="{% url 'workflow:results' %}">Results</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% block nav_item_about %}{% endblock nav_item_about %}" href="#" aria-disabled="true">About</a>
          </li>
        </ul>

        <!-- right navbar -->
        <ul class="navbar-nav me-right mb-2 mb-md-0">

          {% if user.is_authenticated %}

          <li class="nav-item dropdown me-2">
            <a class="nav-link dropdown-toggle active" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="{{ user.profile.image.url }}" alt="{{ user.username }}" width="24" height="24" class="rounded-circle">
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small" aria-labelledby="navbarDropdown">
              <li class="dropdown-item-text">Signed in as</li>
              <li class="dropdown-item-text"><strong>{{user.username}}</strong></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Your templates</a></li>
              <li><a class="dropdown-item" href="#">Your workflows</a></li>
              <li><a class="dropdown-item" href="#">Your runs</a></li>
              <li><a class="dropdown-item" href="#">Your results</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Settings</a></li>
              <li><a class="dropdown-item" href="{% url 'user:profile' %}">Profile</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'user:logout' %}">Sign out</a></li>
            </ul>
          </li>
          
          {% else %}
          
          <li class="nav-item">
            <a class="nav-link {% block nav_item_login %}{% endblock nav_item_login %}" href="{% url 'user:login' %}" aria-disabled="true">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% block nav_item_register %}{% endblock nav_item_register %}" href="{% url 'user:register' %}" aria-disabled="true">Register</a>
          </li>
          {% endif %}

        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
</nav>